---
- name: Install pip
  yum: name=python-pip state=present

- name: Create database user
  no_log: true
  mysql_user: user=root password=F@1zur@@studyroom2308000 priv=*.*:ALL state=present

- name: Create Database
  mysql_db: db=splti state=present