---
- name: Install pip
  yum: name=python-pip state=present

- name: Create database user
  mysql_user: user=admin password=F@1zur@@studyroom2308000 priv=*.*:ALL state=resent

- name: Create Database
  mysql_db: db=splti state=absent