---
# - name: Install pip
#   yum: name=python-pip state=present

# - name: Create database user
#   no_log: true
#   mysql_user:
#       user: splti
#       password: splti@2020
#       priv: *.*:ALL
#       state: present
#       login_unix_socket: /var/lib/mysql/mysql.sock
      
- name: Create Database
  mysql_db: db=ticketing state=present login_user=faizura login_password=F@1zur@@studyroom2308000

- name: Create table User
  state: present
  command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE user (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(128) NOT NULL, email varchar(128) NOT NULL, image varchar(128) NOT NULL, password varchar(256) NOT NULL, role_id int(11) NOT NULL, is_active int(1) NOT NULL, date_created int(11) NOT NULL);' ticketing
  
  