---
# - name: Install pip
#   yum: name=python-pip state=present

# - name: Create database user
#   no_log: true
#   mysql_user:
#       user: splti
#       password: splti@2020
#       priv: *.*:ALL
#       state: present
#       login_unix_socket: /var/lib/mysql/mysql.sock
      
- name: Create Database
  mysql_db: db=ticketing state=present login_user=faizura login_password=F@1zur@@studyroom2308000

# - name: Create table User
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(128) NOT NULL, email varchar(128) NOT NULL, image varchar(128) NOT NULL, password varchar(256) NOT NULL, role_id int(11) NOT NULL, is_active int(1) NOT NULL, date_created int(11) NOT NULL);' ticketing

# - name: Create table user access menu
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_access_menu (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, role_id int(11) NOT NULL, menu_id int(11) NOT NULL);' ticketing
  
# - name: Create table user menu
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_menu (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, menu varchar(128) NOT NULL);' ticketing

# - name: Create table user_prodi
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_prodi (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, prodi varchar(128) NOT NULL);' ticketing

# - name: Create table user respons
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_respons (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, ticket_id int(11) NOT NULL, user_id int(11) NOT NULL, respons text NOT NULL);' ticketing

# - name: Create table user role
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_role (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, role varchar(128) NOT NULL);' ticketing

# - name: Create table user room
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_room (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, room varchar(128) NOT NULL, kode_room varchar(5) NOT NULL);' ticketing

# - name: Create table user submenu
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_sub_menu (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, menu_id int(11) NOT NULL, title varchar(128) NOT NULL, url varchar(128) NOT NULL, icon varchar(128) NOT NULL, is_active int(1) NOT NULL);' ticketing

# - name: Create table user ticket
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_ticket (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, ticket int(7) NOT NULL, room_id int(11) NOT NULL UNIQUE, computer varchar(5) NOT NULL, kategori varchar(128) NOT NULL, deskripsi text NOT NULL, image varchar(15) NOT NULL, user_id int(10), status_ticket int(2) NOT NULL, tgl_daftar date NOT NULL, respons text NOT NULL);' ticketing

# - name: Create table user token
#   command: mysql -u faizura -pF@1zur@@studyroom2308000 -e 'CREATE TABLE IF NOT EXISTS user_token (id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, email varchar(128) NOT NULL, token varchar(128) NOT NULL, date_created int(11) NOT NULL);' ticketing

- name: import the database
  mysql_db:
      name: ticketing
      state: import
      target: /home/centos/sql/ticketing.sql
      login_host: 3.94.21.105
      login_user: root
      login_password: 'F@1zur@@studyroom2308000'